project:
  name: TBD_PROJECT_NAME
  author: TBD_AUTHOR
  date: 2025-10-06
sim:
  N_samples: 1000        # Monte Carlo sample count (initial placeholder)
  time_horizon_s: 300    # total simulated time [s]
  dt_s: 1.0              # timestep [s]
  random_seed: 12345
  B_bootstrap: 500       # bootstrap resamples for CI
  rho_tol: 0.05          # tolerance for correlation validation (abs diff)
  delta_pct: 10          # OAT sensitivity perturbation percent
modes: ["open","urban","tunnel"]
correlations:
  use_copula: true
  type: gaussian
  # Square correlation matrix placeholder (sensors: gnss_bias, gnss_noise, odo_scale, imu_acc_bias, imu_gyro_bias, map_ref)
  rho_matrix:
    - [1.0, 0.2, 0.1, 0.0, 0.0, 0.1]
    - [0.2, 1.0, 0.15, 0.05, 0.0, 0.1]
    - [0.1, 0.15, 1.0, 0.05, 0.05, 0.0]
    - [0.0, 0.05, 0.05, 1.0, 0.2, 0.0]
    - [0.0, 0.0, 0.05, 0.2, 1.0, 0.0]
    - [0.1, 0.1, 0.0, 0.0, 0.0, 1.0]
sensors:
  gnss:
    bias_m:
      dist: normal
      mean: 0.5     # m (placeholder)
      std: 1.0      # m
    noise_m:
      dist: lognormal
      mean: 0.0     # underlying normal mean
      sigma: 0.3    # underlying normal std
    outage_prob: 0.02  # probability per timestep of GNSS outage
  odometry:
    scale_error_ppm:
      dist: normal
      mean: 100.0   # ppm
      std: 30.0     # ppm
    noise_mps:
      dist: normal
      mean: 0.0
      std: 0.05     # m/s
    drift_mps2:
      dist: normal
      mean: 0.0
      std: 0.002    # m/s^2
  imu:
    accel_bias_mps2:
      dist: normal
      mean: 0.01
      std: 0.02
    gyro_bias_dps:
      dist: normal
      mean: 0.05
      std: 0.05
    noise_density:
      dist: normal
      mean: 0.0
      std: 0.1
  balise:
    position_noise_m:
      dist: normal
      mean: 0.0
      std: 0.3
    detection_prob: 0.95
  map:
    ref_error_m:
      dist: normal
      mean: 0.0
      std: 0.5
fusion:
  latency_ms: 100
  timestamp_jitter_ms: 20
  filter_proxy: ekf_simple

# Notes:
# - All parameter values are placeholders pending Phase 1 interview & file scan.
# - Distributions: allowed keys (normal, uniform, lognormal, laplace, student_t, empirical).
# - For lognormal: 'mean' and 'sigma' refer to underlying normal parameters.
