project:
  name: ErrorPropagation_Localisation_bad_weather
  author: TBD_AUTHOR
  date: 2025-10-09
sim:
  N_samples: 10000
  time_horizon_s: 3600
  dt_s: 0.1
  random_seed: 12345
  B_bootstrap: 500
  rho_tol: 0.05
  delta_pct: 10
morphology:
  speed_range_kmh: [0, 45]
  accel_max_mps2: 0.5
  route_mix_pct: {open: 70, urban: 30, tunnel: 0}
modes: ["open","urban","tunnel"]
correlations:
  use_copula: true
  type: gaussian
  variables: [map, gnss, balise, odometry, imu]
  rho_matrix:
    - [1.0, 0.80, 0.65, 0.10, 0.05]
    - [0.80, 1.0, 0.30, 0.25, 0.20]
    - [0.65, 0.30, 1.0, 0.80, 0.15]
    - [0.10, 0.25, 0.80, 1.0, 0.40]
    - [0.05, 0.20, 0.15, 0.40, 1.0]
sensors:
  balise:
    latency_ms: {dist: trunc_normal, mean: 11.0, std: 2.5, lower: 6.0, upper: 16.0}  # leicht erhöhte Latenz & Varianz
    early_detection: {enabled: true, c1_ms_per_mps: 0.5, cap_ms: 4.0, d_const_m: 0.08}  # schlechteres Wetter reduziert wirksamen Offset
    antenna_offset_m: {dist: normal, mean: 0.0, std: 0.022}  # leichte zusätzliche Instabilität
    em_disturbance_m: {dist: rayleigh, sigma: 0.014}         # mehr EM-Störung
    multipath_tail_m: {dist: trunc_exp, lambda: 0.04, cap: 0.10, weight: 0.25}  # stärkerer Tail
    weather_uniform_m: {dist: uniform, low: -0.03, high: 0.03}  # Schlechtes Wetter doppelt so breit
    detection:
      p_detect_nominal: 0.9998   # minimal erhöhte Misswahrscheinlichkeit
      markov: {use: false, p_ok_to_deg: 2.0e-6, p_deg_to_ok: 0.01, p_detect_degraded: 0.94}
    lateral: {dist: normal, mean: 0.032, std: 0.011}  # etwas höhere Streuung lateral
  odometry:
    quant_step_m: 0.0134
    residual_circumference_m: {dist: uniform, low: -0.025, high: 0.025}  # Wetterbedingte kleine Ausweitung
    drift_per_km_m: 0.012   # leicht höherer Drift
  map:
    longitudinal:
      ref_error: {dist: normal, mean: 0.0, std: 0.021}  # geringfügig schlechtere Projektion
      interpolation: {dist: trunc_exp, lambda: 0.02, cap: 0.06, weight: 0.40}
      scale: {dist: normal, mean: 0.0, std: 0.0007, activation_distance_m: 2000}
    lateral:
      ref_error: {dist: normal, mean: 0.0, std: 0.016}
  gnss:
    modes:
      open:
        bias: {dist: normal, mean: 0.0, std: 0.30}   # Bias +20%
        bias_lat: {dist: normal, mean: 0.0, std: 0.26}
        noise: {dist: normal, mean: 0.0, std: 0.40}  # Rauschen +33%
        noise_lat: {dist: normal, mean: 0.0, std: 0.36}
        outage_prob: 0.015  # etwas mehr kurzfristige Ausfälle
      urban:
        bias: {dist: normal, mean: 0.0, std: 0.60}
        bias_lat: {dist: normal, mean: 0.0, std: 0.54}
        noise: {dist: normal, mean: 0.0, std: 1.00}
        noise_lat: {dist: normal, mean: 0.0, std: 0.94}
        multipath_tail: {dist: trunc_exp, lambda: 1.6, cap: 3.5, weight: 0.15}
        outage_prob: 0.07
      tunnel:
        outage_prob: 1.0
        hold_last_valid_s: 30.0
  imu:
    accel_bias_mps2: {dist: normal, mean: 0.0, std: 0.006, rw_tau_s: 900}
    gyro_bias_dps: {dist: normal, mean: 0.0, std: 0.024, rw_tau_s: 900}
    accel_noise_density_mps2_sqrtHz: 0.055
    gyro_noise_density_dps_sqrtHz: 0.011
    position_bias_factor: 0.001
  fusion:
    rule_based: true
    filter_proxy: rule_based_4rules
    blend_steps: 5
    latency_ms: {dist: trunc_normal, mean: 22.0, std: 6.0, lower: 10.0, upper: 38.0}
    timestamp_jitter_ms: 6.0
    interval:
      use_additive_global: true

secure_interval:
  method: additive_p99
  conservative: true

reporting:
  metrics: [rmse_longitudinal, rmse_lateral, p50, p90, p95, p99]
  export_formats: [csv]
